### ISSUE TITLE
Add GitHub Actions YAML file

### ISSUE THREAD

**Issue by anton-trunov** [tact-lang/tact-template#33]
This should allow users to automatically build contracts, run tests and run the [misti](https://github.com/nowarp/misti) static analyzer if they host their projects on GitHub.

Related Blueprint issue: https://github.com/ton-org/create-ton/issues/22

**Comment by jubnzv** [comment]
I would help at least with Misti integration. The configuration process should match the instruction: https://nowarp.io/tools/misti/docs/tutorial/ci-cd.

Perhaps, we should also restrict the default warning severity level to Medium (`-m medium`) in order to make it less noisy.

**Comment by anton-trunov** [comment]
@jubnzv Feel free too add CI to this repo, any help would be greatly appreciated

**Comment by jubnzv** [comment]
I would implement Misti integration as a separate GitHub action: https://github.com/nowarp/misti/issues/153.

However, I would need to prepare an additional minor release for Misti to make the analysis less noisy and more configurable. At a minimum, I would need:
- The `--min-severity` option: https://github.com/nowarp/misti/commit/79e1a84e9c4aa11eac583cf98a9f985d13ce25e7
- Fixes for false positives I've recently found: https://github.com/nowarp/misti/issues/148 and https://github.com/nowarp/misti/issues/149
- Poor man's warning suppression: https://github.com/nowarp/misti/issues/152

Additionally, I would improve blueprint integration to enable running the GitHub action for blueprint plugins:
- https://github.com/nowarp/blueprint-misti/issues/6

After implementing this I suggest to create an another minor release (since my roadmap for more valuable detectors hasn't approved: https://github.com/ton-society/grants-and-bounties/issues/777), release a github action and integrate it to the Tact template.

**Comment by jubnzv** [comment]
Otherwise, if we need to implement this ASAP, we can add a CI without running Misti and simply include it to the `package.json` adding usage instructions.

**Comment by anton-trunov** [comment]
We don't really need it ASAP, let's solve it the proper way.

**Comment by jubnzv** [comment]
Alright, here is my plan for the next minor release that includes adding the GitHub action: https://github.com/nowarp/misti/milestone/8.

**Comment by jubnzv** [comment]
Here is the grammar fix:

I developed the initial implementation of a GitHub Action for Misti, but I decided not to publish it. Here are the problems:
- The blueprint configuration is too complicated: we need a flag if the blueprint is used, the name/names of the blueprint projects to analyze, and a command to run the blueprint (e.g., `npx blueprint misti`, `yarn blueprint misti`, etc.). The user also has to manually install and configure the `blueprint-misti` plugin before running it. This overcomplicates things, and a single `run` action would be more explicit and simpler.
- We still need to specify arguments for the Misti command or keep the action's configuration up-to-date with the current CLI options in Misti, which requires creating custom options.
- The GitHub Actions runner for Node doesn't support Node.js 20+. Therefore, the implementation must be wrapped in Docker.

Overall, at this time, a separate GitHub Action for Misti is not feasible and only complicates things. It might become simpler later when we eliminate extra configuration options, introduce execution without Tact configuration, hack Blueprint, and when Node22 becomes available for GitHub Actions. For now, it makes no sense.

I will prepare a CI in this repo without using the `misti-action` package.
